<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class TokenSeeder extends Seeder
{
    public function run(): void
    {
        $superAdmin = User::where('role', 'super_admin')->first();
        $admins = User::where('role', 'admin_perijinan')->get();
        $viewers = User::where('role', 'viewer')->get();

        if (!$superAdmin) {
            return;
        }

        // GROUP 1: UNUSED TOKENS (10 tokens)
        for ($i = 1; $i <= 10; $i++) {
            $rawToken = 'seed_unused_token_'.$i;
            $tokenHash = hash('sha256', $rawToken); // Using SHA256 for lookup as per migration
            
            DB::table('registration_tokens')->updateOrInsert(
                ['token_lookup' => $tokenHash],
                [
                    'token_hash' => bcrypt($rawToken),
                    'token_encrypted' => encrypt($rawToken),
                    'created_by' => $superAdmin->id,
                    'status' => 'active',
                    'used_by' => null,
                    'used_by_security_code' => null,
                    'used_at' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        // GROUP 2: USED TOKENS (Ensure each seeded viewer gets exactly one token)
        foreach ($viewers as $viewer) {
            $rawToken = 'seed_used_token_'.$viewer->security_code;
            $tokenHash = hash('sha256', $rawToken);
            
            DB::table('registration_tokens')->updateOrInsert(
                ['token_lookup' => $tokenHash],
                [
                    'token_hash' => bcrypt($rawToken),
                    'token_encrypted' => encrypt($rawToken),
                    'created_by' => $superAdmin->id,
                    'status' => 'used',
                    'used_by' => $viewer->id,
                    'used_by_security_code' => $viewer->security_code,
                    'used_at' => now(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        // GROUP 3: RECENT TOKENS (3 tokens generated by admins)
        if ($admins->count() > 0) {
            for ($i = 1; $i <= 3; $i++) {
                $admin = $admins[$i % $admins->count()];
                $rawToken = 'seed_recent_token_'.$i;
                $tokenHash = hash('sha256', $rawToken);
                
                DB::table('registration_tokens')->updateOrInsert(
                    ['token_lookup' => $tokenHash],
                    [
                        'token_hash' => bcrypt($rawToken),
                        'token_encrypted' => encrypt($rawToken),
                        'created_by' => $admin->id,
                        'status' => 'active',
                        'used_by' => null,
                        'used_by_security_code' => null,
                        'used_at' => null,
                        'created_at' => now()->subHours(rand(1, 24)),
                        'updated_at' => now(),
                    ]
                );
            }
        }
    }
}
